### ISSUE TITLE
parse() returns null

### ISSUE THREAD

**Issue by ekkis** [witem/phoneNumberLite.js#1]
today I came across a number that causes the parsing function to return null.  the number belongs to Morocco and is a valid number as evidenced in its use by this site: https://receive-smss.com/ which allows anyone to send texts to it 

```bash
$ node -e 'PNL=require("phonenumberlite"); console.log(PNL.parse("+212770540034"))'
null
```

**Comment by ekkis** [comment]
the problem seems to be that the definition for Morocco is missing both `.possiblePattern` or `.nationalPattern`, which according to this code:
```js
function ParseNationalNumber(number, md) {
    if (!md.possiblePattern.test(number) ||
        !md.nationalPattern.test(number)) {
      return null;
```
is required to return a meaningful value.  I do not understand what these patters are but apparently it needs both and Morocco doesn't have them.  perhaps that sheds some light on the matter

**Comment by witem** [comment]
Hi @ekkis 
Thanks for your issue. It should be fixed in version `1.0.0`. But there also can be possible breaking changes for other phone number formats because some tests start to fail: https://github.com/witem/phoneNumberLite.js/pull/2

![зображення](https://user-images.githubusercontent.com/1782530/197384293-0521276d-d75e-4bcf-ab05-c4873a95f55d.png)

**Comment by ekkis** [comment]
I upgraded and can see the changes you made in my local code, however, I still get a `null` on the call, but for a number in Kazakhstan: `+7755722696`

**Comment by witem** [comment]
@ekkis because you missed one 7 in number, correct number is: `+77755722696`

**Comment by ekkis** [comment]
ah! you're correct.  thank you, and thanks for the prompt attention to the package.  all good now (though some numbers are getting formatted differently now so I have to go fix my test suite)

**Comment by ekkis** [comment]
strangely, the results seem to be inconsistent.  here's output from my unit tests:
```json
         {
           "loc": "Germany"
      -    "nbr": "+49 15 207831169"
      +    "nbr": "+49 1520 7831169"
         }
         {
           "loc": "Germany"
      -    "nbr": "+49 152 07829731"
      +    "nbr": "+49 1520 7829731"
         }
         {
           "loc": "Germany"
           "nbr": "+49 1520 7829823"
         }
```
which shows the newly returned values in 3 different formats!

**Comment by ekkis** [comment]
India shows some similar disparities:
```json
         {
           "loc": "India"
           "nbr": "+91 7428 730 894"
         }
         {
           "loc": "India"
      -    "nbr": "+91 742 873 1210"
      +    "nbr": "+91 7428 731 210"
         }
```

**Comment by witem** [comment]
This is because of many changes in the original lib - https://github.com/google/libphonenumber. I think for you, it would be better to find some other lib that is more actively maintained) Because as I see, there are some problems with some exceptional cases.

**Comment by ekkis** [comment]
seems to me this library is pretty actively maintained :)

for now I've patched my own code to simply skip phone numbers that fail to parse
